"""empty message

Revision ID: 18c99447b0f6
Revises: a69de898e908
Create Date: 2018-10-31 22:13:17.498837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c99447b0f6'
down_revision = 'a69de898e908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_test_key', 'users', type_='unique')
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_test_key', 'users', ['test'])
    # ### end Alembic commands ###
