"""empty message

Revision ID: 8daa3c937599
Revises: 2b727226d482
Create Date: 2018-11-15 21:55:59.863187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8daa3c937599'
down_revision = '2b727226d482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_ability',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('ability_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('users_roles')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('roles', 'abilities_text')
    op.drop_column('users', 'abilities_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('abilities_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('abilities_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_table('users_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='users_roles_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_roles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_roles_pkey'),
    sa.UniqueConstraint('user_id', 'role_id', name='users_roles_user_id_role_id_key')
    )
    op.drop_table('user_role')
    op.drop_table('role_ability')
    op.drop_table('abilities')
    # ### end Alembic commands ###
