"""empty message

Revision ID: ab0913878a05
Revises: 
Create Date: 2018-10-19 19:57:55.535916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab0913878a05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index('ix_transaction_tasks_transaction_id', table_name='transaction_tasks')
    op.drop_table('transaction_tasks')
    op.create_unique_constraint(None, 'anthill_sessions', ['session_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anthill_sessions', type_='unique')
    op.create_table('transaction_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('started', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'STARTED', 'SUCCESSFUL', 'FAILED', 'RESUMED', 'ROLLBACK_STARTED', 'ROLLBACK_SUCCESSFUL', 'ROLLBACK_FAILED', name='status'), autoincrement=False, nullable=False),
    sa.Column('timeout', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_commited', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='transaction_tasks_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transaction_tasks_pkey')
    )
    op.create_index('ix_transaction_tasks_transaction_id', 'transaction_tasks', ['transaction_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('started', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'STARTED', 'SUCCESSFUL', 'FAILED', 'RESUMED', 'ROLLBACK_STARTED', 'ROLLBACK_SUCCESSFUL', 'ROLLBACK_FAILED', name='status'), autoincrement=False, nullable=False),
    sa.Column('timeout', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_commited', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    # ### end Alembic commands ###
