"""
Initial migration

Revision ID: bc5d3cb6f581
Revises: 
Create Date: 2018-08-30 20:02:09.904876
"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield


# revision identifiers, used by Alembic.
revision = 'bc5d3cb6f581'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anthill_sessions',
    sa.Column('session_key', sa.String(length=40), nullable=False),
    sa.Column('session_data', sa.Text(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    sa.UniqueConstraint('session_key')
    )
    op.create_index(op.f('ix_anthill_sessions_expire_date'), 'anthill_sessions', ['expire_date'], unique=False)
    op.create_table('deployment_methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('local', 'keycdn', name='names'), nullable=False),
    sa.Column('data', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('deployment_method_id', sa.Integer(), nullable=False),
    sa.Column('filters_scheme', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=False),
    sa.Column('payload_scheme', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_method_id'], ['deployment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_deployment_method_id'), 'applications', ['deployment_method_id'], unique=False)
    op.create_table('application_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_versions_application_id'), 'application_versions', ['application_id'], unique=False)
    op.create_table('bundle_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PUBLISHING', 'PUBLISHED', 'ERROR', name='statuses'), nullable=False),
    sa.Column('hash_types', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['application_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_groups_version_id'), 'bundle_groups', ['version_id'], unique=False)
    op.create_table('bundles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('hash', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=False),
    sa.Column('filter', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'UPLOADED', 'DELIVERING', 'DELIVERED', 'ERROR', name='statuses'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['bundle_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_bundles_group_id'), 'bundles', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bundles_group_id'), table_name='bundles')
    op.drop_table('bundles')
    op.drop_index(op.f('ix_bundle_groups_version_id'), table_name='bundle_groups')
    op.drop_table('bundle_groups')
    op.drop_index(op.f('ix_application_versions_application_id'), table_name='application_versions')
    op.drop_table('application_versions')
    op.drop_index(op.f('ix_applications_deployment_method_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('deployment_methods')
    op.drop_index(op.f('ix_anthill_sessions_expire_date'), table_name='anthill_sessions')
    op.drop_table('anthill_sessions')
    # ### end Alembic commands ###
